// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"登录","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/userCenter","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/userMessage","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/welcome","name":"欢迎","icon":"WechatOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin","name":"管理页","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/admin","redirect":"/admin/sub-page","parentId":"6","id":"7"},"8":{"path":"/admin/upload","name":"上传成绩数据","parentId":"6","id":"8"},"9":{"path":"/admin/course","name":"课程管理","parentId":"6","id":"9"},"10":{"path":"/admin/student","name":"学生管理","parentId":"6","id":"10"},"11":{"path":"/admin/teacher","name":"教师管理","parentId":"6","id":"11"},"12":{"path":"/courseSelect","name":"选课页面","icon":"smile","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"/course-recommendations","name":"课程推荐","icon":"bulb","parentId":"ant-design-pro-layout","id":"13"},"14":{"path":"/selected","name":"已选课程页面","icon":"smile","parentId":"ant-design-pro-layout","id":"14"},"15":{"path":"/schedule","name":"我的课程表","icon":"calendar","parentId":"ant-design-pro-layout","id":"15"},"16":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"16"},"17":{"path":"*","layout":false,"id":"17"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__UserCenter" */'@/pages/User/UserCenter.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__User__UserMessage" */'@/pages/User/UserMessage.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__admin__Admin" */'@/pages/admin/Admin.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__admin__Course" */'@/pages/admin/Course.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__admin__Student" */'@/pages/admin/Student.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__admin__Teacher" */'@/pages/admin/Teacher.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__CourseSelectionPage" */'@/pages/CourseSelectionPage.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__CourseRecommendation" */'@/pages/CourseRecommendation.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__SelectedCoursesPage" */'@/pages/SelectedCoursesPage.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__SchedulePage" */'@/pages/SchedulePage.tsx')),
'16': React.lazy(() => import('./EmptyRoute')),
'17': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/home/pengyiju/code/lunwen/lunwen/selsect-course/selsect-course/cloudCalculate-front/myapp/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
