// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import WechatOutlined from 'D:/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/WechatOutlined';
import CrownOutlined from 'D:/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import SmileOutlined from 'D:/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import BulbOutlined from 'D:/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/BulbOutlined';
import CalendarOutlined from 'D:/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
export default { WechatOutlined, CrownOutlined, SmileOutlined, BulbOutlined, CalendarOutlined };
