// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import WechatOutlined from '/workspace/node_modules/@ant-design/icons/es/icons/WechatOutlined';
import CrownOutlined from '/workspace/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import SmileOutlined from '/workspace/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import BulbOutlined from '/workspace/node_modules/@ant-design/icons/es/icons/BulbOutlined';
import CalendarOutlined from '/workspace/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
export default { WechatOutlined, CrownOutlined, SmileOutlined, BulbOutlined, CalendarOutlined };
