apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-05-04T08:57:56Z"
  labels:
    kubernetes.io/metadata.name: select-course
  name: select-course
  resourceVersion: "37"
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
