// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import WechatOutlined from '/home/pengyiju/code/lunwen/lunwen/selsect-course/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/WechatOutlined';
import CrownOutlined from '/home/pengyiju/code/lunwen/lunwen/selsect-course/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import SmileOutlined from '/home/pengyiju/code/lunwen/lunwen/selsect-course/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import BulbOutlined from '/home/pengyiju/code/lunwen/lunwen/selsect-course/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/BulbOutlined';
import CalendarOutlined from '/home/pengyiju/code/lunwen/lunwen/selsect-course/selsect-course/cloudCalculate-front/myapp/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
export default { WechatOutlined, CrownOutlined, SmileOutlined, BulbOutlined, CalendarOutlined };
